### ISSUE TITLE
Newtonsoft.Json 10.0.0 with latest version

### ISSUE THREAD

**Issue by Ideki** [seraphx2/ESI.NET#42]
Hi,
I am having issue using the ESi.Net as it is dependent on Newtonsoft.Json 10.0.0
Or that version is not available anymore.
There 9.0.1 then 10.0.1

Could you either update to the latest version or simply get rid of the dependency altogether?
I would advise switching to System.Text.Json for serialization/deserialization as it has been proven to be faster and more reliable.

**Comment by seraphx2** [comment]
ESI.NET itself does not have a dependency on Newtonsoft.Json. It is definitely used to serialize/deserialize datasets, but the actual dependency references are only in official .NET Core libraries. The .NET Core libraries that are being used are directly referencing 10.0.3.

Usually when this error is given, it's because the versions don't match in core dependencies that can't be changed and something that the developer is using, be it a third party or their own reference. Sometimes, simply forcing your own dependency in the NuGet manager to the common version (in this case 10.0.3) resolves that issue.

**Comment by seraphx2** [comment]
Oops, didn't mean to close this. I think I will attempt to remove Json.NET.
